### ISSUE TITLE
Front-end developer @ BandLab

### ISSUE THREAD

**Issue by pioug** [SingaporeJS/jobs#21]
[![image](https://user-images.githubusercontent.com/3654180/35896436-25ed7e2c-0bf7-11e8-84e6-7aa2a200a07d.png)](https://www.bandlab.com)

Hello! I am Gilles from [BandLab](https://www.bandlab.com). We are looking for a front-end developer to join our team in Singapore. As a UI developer, you will collaborate with designers to create outstanding user experiences. Along the way, you will learn some of the most interesting techniques around audio and signal processing.

## Responsibilities

- Develop BandLab web applications and internal tools
- Work with UI/UX designers to implement changes and new features
- Troubleshoot and resolve issues with existing codes
- Participate in code reviews
- Maintain codebase and build tools
- Monitor application stability and security

## Desired Skills and Experience

- Fluent in HTML/CSS + JavaScript
- Strong knowledge of web performances
- Willingness to learn in depth: AngularJS, React, SCSS, Gulp, Webpack, Git
- Advanced usage of debugging and profiling tools
- Understanding of the current state of front-end tooling
- Experience with Node.js and npm ecosystem for front-end purpose
- Ability to communicate effectively with both technical and non-technical individuals
- Familiarity with Web Audio API is a plus

## Perks

- Sharp, motivated co-workers in a fun office environment
- Challenges to express and develop your creativity by bringing a unique and new experience to the world
- Multicultural environment at the heart of cosmopolitan Singapore
- Free choice of your working equipment (Are you Windows, Mac or Linux?)
- Discounts at related musical instrument stores
- Relocation package to Singapore

If this sounds like you, please send a CV and covering letter to hr@bandlab.com.

**Comment by notthetup** [comment]
🔉
