### ISSUE TITLE
D3 Tutor - part time/hourly

### ISSUE THREAD

**Issue by katannyak** [SingaporeJS/jobs#33]
Hi, I'm a scientist/researcher at National University of Singapore wanting to create some interactive charts of our data using D3 (v5). If you're proficient at D3 and would like to earn some extra cash in basic D3 tutoring, please contact me. Thanks!

**Comment by sonnenhaft** [comment]
Hi, worked pretty much with d3js, but v3 I guess. 
What you will build in end of tutorial?
