### ISSUE TITLE
ThoughtWorks Recruitment Open House - 7 Sept 7pm

### ISSUE THREAD

**Issue by jonaliang** [SingaporeJS/jobs#4]
Calling software developers -  join us for a recruitment open house. 

Come visit our office, chat with ThoughtWorkers, work together on an activity and grab a bite. 
Register at http://bit.ly/2vTAALN

Registrations close in 3 days on 3 Sept 2017!

![20170821_v2images-sg-04](https://user-images.githubusercontent.com/13519470/29905136-662061a2-8e3f-11e7-84a3-e5188d8ca6b6.png)

**Comment by jsstrn** [comment]
Closed as this event has passed
